embed_assets: on
template_function: _.template

javascripts:
  libs:
    - public/javascripts/vendor/jquery.js
    - public/javascripts/vendor/jquery.cookie.js
    - public/javascripts/vendor/jquery-ui.js
    - public/javascripts/vendor/underscore.js
    - public/javascripts/vendor/backbone.js
    - public/javascripts/vendor/backbone-localstorage.js

  templates:
    - app/templates/**/*.jst

  core:
    - public/javascripts/workspace.js
    - public/javascripts/stickies.js
    - public/javascripts/boards.js
    - public/javascripts/notifications.js
    - public/javascripts/bootstrap.js
