defaults: &defaults
  host: db
  port: 27017

development:
  <<: *defaults
  database: quadro_development

test:
  <<: *defaults
  database: quadro_test

production:
  uri: <%= ENV["MONGOLAB_URI"] %>
