development:
  sandbox: true
  username: rainer_1314803572_biz_api1.hotmail.com
  password: 1314803621
  signature: ALvy2nAO-RL59i6Hdek--E88Wz0AAEJ8oo2QHd1i.xRRZahaolVEYz2I

production:
  sandbox: false
  username: rainerborene_api1.gmail.com
  password: RKNLHWE896L8H48L
  signature: AFcWxV21C7fd0v3bYYYRCpSSRl31AMk-C1WANQ1nP-kzzZO5LssZykkq
